# Generated by Django 3.2.7 on 2023-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyviews',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
